INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("AC/DC", "High Voltage", 1973, 1976, 1, "Pochette trouee");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("AC/DC", "Let There Be Rock", 1977, 1977, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("AC/DC", "Power Age", 1978, 1978, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("AC/DC", "Highway To Hell", 1979, 1979, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("AC/DC", "Back In Black", 1980, 1980, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("AC/DC", "For Those About To Rock", 1981, 1981, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("AC/DC", "Black Ice", 2008, 2008, 2, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("AC/DC", "Live At River Plate", 2011, 2012, 3, "Disques rouges translucides");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Apocalyptica", "Shadowmaker", 2015, 2015, 2, "version CD fournie");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Alan Parson Project", "The Turn Of A Friendly Card", 1980, 1980, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Alan Parson Project", "Eye In The Sky", 1982, 1982, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Carnaby Group", "Integral Cover Version Of Beatles", 1976, 1976, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Beatles", "Abbey Road", 1969, 1969, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Beatles", "1962-1966", 1973, 1973, 2, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Beatles", "1967-1970", 1973, 1973, 2, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Bernard Lavilliers", "O Gringo", 1980, 1980, 2, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Bernard Lavilliers", "Nuit d''Amour", 1981, 1981, 2, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Bernard Lavilliers", "etat d''Urgence", 1983, 1983, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Bernard Lavilliers", "Voleur de Feu", 1986, 1986, 2, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Bob Dylan", "Street Legal", 1978, 1978, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Bob Marley", "Exodus", 1977, 1977, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, nb_disques, commentaire) VALUES ("Creedance Clearwater Revival", "Pendulum", 1970, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, nb_disques, commentaire) VALUES ("Creedance Clearwater Revival", "Willy And The Poorboys", 1969, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("David Bowie", "Lets Dance", 1983, 1983, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Deep Purple", "Fireball", 1971, 1971, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Deep Purple", "In Rock", 1970, 1978, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Deep Purple", "Machine Head", 1972, 1972, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Dire Straits", "Communique", 1979, 1979, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Dire Straits", "Love Over Gold", 1982, 1982, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Dire Straits", "Money For Nothing", 1988, 1988, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Dire Straits and Mark Knopfler", "Private Investigations", 2005, 2005, 2, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Epica", "The Divine Conspirancy", 2007, 2017, 2, "edition speciale anniversaire limitee 300exps - disques verts");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Epica", "The Quantum Enigma", 2014, 2014, 2, "achete sur la tournee - disques argentes");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Epica", "The Holographic Principle", 2016, 2016, 2, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Epica", "The Solace System", 2017, 2017, 2, "edition limitee 300exps - disques transparents");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Eric Serra", "Subway", 1985, 1985, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Genesis", "Duke", 1980, 1980, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Iron Maiden", "Iron Maiden", 1980, 1980, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Jean-Michel Jarre", "Oxygene", 1976, 1976, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Jean-Michel Jarre", "Equinoxe", 1978, 1978, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Jean-Michel Jarre", "Les Chants Magnetiques", 1981, 1981, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Jean-Michel Jarre", "Les Concerts En Chine", 1982, 1982, 2, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Jean-Michel Jarre", "En Concert Houston Lyon", 1987, 1987, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, nb_disques, commentaire) VALUES ("J.S. Bach", "Concerto Pour Violons et Orchestre", 1735, 1, "");
INSERT INTO Vinyles (artiste, titre, nb_disques, commentaire) VALUES ("J.S. Bach", "Integrale de l''oeuvre d''orgue  vol2", 6, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Jimmy Hendrix", "Axis Bold As Love", 1967, 1967, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Led Zeppelin", "II", 1969, 1970, 1, "Serie de luxe - disque beige");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Led Zeppelin", "IV", 1971, 1971, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Led Zeppelin", "In Through The Out Door", 1979, 1979, 1, "Seulement la jaquette - coloration à l''eau");
INSERT INTO Vinyles (artiste, titre, nb_disques, commentaire) VALUES ("Louis Armstrong", "Louis Armstrong", 1, "");
INSERT INTO Vinyles (artiste, titre, nb_disques, commentaire) VALUES ("Ludwig Von Beethoven", "Integrale des 9 symphonies", 6, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Madness", "One Step Beyond", 1979, 1979, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Metallica", "Kill ''em All", 1983, 1983, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Metallica", "Ride The Lightning", 1984, 1984, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Metallica", "Master Of Puppets", 1986, 1986, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Metallica", "Metallica", 1991, 1991, 2, "edition collector - diques verts");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Metallica", "Hardwired To Self Destruct", 2016, 2016, 2, "disques rouges");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Mike Oldfield", "Crises", 1983, 1983, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Michael Jackson", "Thriller", 1982, 1982, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Midnigh Oil", "Diesel And Dust", 1987, 1987, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Nightwish", "Wishmaster", 2000, 2000, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Nightwish", "Century Child", 2002, 2015, 2, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Nightwish", "Once", 2004, 2011, 2, "Disques marbres - poster inclu");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Nightwish", "Dark Passion Play", 2007, 2013, 2, "Poster inclu");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Nightwish", "Imaginaerum", 2011, 2011, 2, "Disques transparents");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Nightwish", "Endless Forms Most Beautiful", 2015, 2015, 2, "edition limitee numerotee 51/200 jaune");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Pat Benetar", "In The Heat Of The Night", 1979, 1979, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Phil Collins", "Face Value", 1981, 1981, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Pink Floyd", "Meddle", 1971, 1971, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Pink Floyd", "The Dark Side Of The Moon", 1973, 1973, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Pink Floyd", "The Division Bell", 1994, 2014, 2, "edition Anniversaire");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Pink Floyd", "The Wall", 1979, 1979, 2, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Pink Floyd", "Whish You Were Here", 1975, 1975, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Police", "Outlandos d''Amour", 1978, 1978, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Police", "Regatta De Blanc", 1979, 1979, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Police", "Zenyatta Mondatta", 1980, 1980, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Police", "Ghost In The Machine", 1981, 1981, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Police", "Synchronicity", 1983, 1983, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Queen", "Live Magic", 1986, 1986, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Queen", "News Of The World", 1977, 1977, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Rolling Stones", "Goats Head Soup", 1973, 1973, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Rolling Stones", "Some Girls", 1978, 1978, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Rolling Stones", "Undercover", 1983, 1983, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Saxon", "Strong Arm Of The Law", 1980, 1980, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Scorpions", "Crazy World", 1990, 1990, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Scorpions", "Lonesome Crow", 1972, 1982, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Scorpions", "Gold Ballads", 1984, 1984, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Simon And Garfunkel", "Greatest Hits", 1972, 1972, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Simon And Garfunkel", "The Concert In Central Park", 1982, 1982, 2, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Status Quo", "Quo", 1974, 1974, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Status Quo", "Whatever You Want", 1979, 1979, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Sting", "The Dream Of The Blue Turtles", 1985, 1985, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Supertramp", "Crime Of The Century", 1974, 1974, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Supertramp", "Even In The Quietest Moments...", 1977, 1977, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Supertramp", "Breakfast In America", 1979, 1979, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Tears For Fears", "Songs From The Big Chair", 1985, 1985, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition) VALUES ("Telephone", "Crache Ton Venin", 1979, 1979);
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Telephone", "Au Coeur De La Nuit", 1980, 1980, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Telephone", "Dure Limite", 1982, 1982, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Telephone", "Un Autre Monde", 1984, 1984, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Trust", "Repression", 1980, 1980, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Trust", "Marche Ou Crève", 1981, 1981, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("U2", "The Unforgettable Fire", 1984, 1984, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("U2", "Under A Blood Red Sky", 1983, 1983, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Van Hallen", "Van Hallen", 1978, 1978, 1, "Disque uniquement");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("Wings", "London Town", 1978, 1978, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Who", "Best Of Who", 1970, 1970, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("The Who", "Who''s Next", 1971, 1971, 1, "");
INSERT INTO Vinyles (artiste, titre, annee_sortie, annee_edition, nb_disques, commentaire) VALUES ("ZZ Top", "Eliminator", 1983, 1983, 1, "");